name: Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: npm ci && npm run demo:build
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Deploy Demo to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: demo
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}